export interface MockAd {
  id: string;
  platform: string;
  brand: string;
  brandLogo?: string;
  imageUrl: string;
  copyText: string;
  category: string;
  format: string;
  likes: number;
  comments: number;
  shares: number;
  startDate: string;
  endDate?: string;
  isActive: boolean;
  country: string;
}

export const mockAds: MockAd[] = [
  {
    id: "1",
    platform: "instagram",
    brand: "올리브영",
    imageUrl: "/images/placeholder-ad.svg",
    copyText: "지금 이 가격, 다시 없어요! 올영세일 최대 70% 할인",
    category: "뷰티",
    format: "이미지",
    likes: 2340,
    comments: 186,
    shares: 45,
    startDate: "2026-03-01",
    endDate: "2026-03-15",
    isActive: false,
    country: "KR",
  },
  {
    id: "2",
    platform: "facebook",
    brand: "무신사",
    imageUrl: "/images/placeholder-ad.svg",
    copyText: "이번 봄, 가장 먼저 입는 신상 컬렉션",
    category: "패션",
    format: "캐러셀",
    likes: 1520,
    comments: 89,
    shares: 32,
    startDate: "2026-03-10",
    isActive: true,
    country: "KR",
  },
  {
    id: "3",
    platform: "instagram",
    brand: "배달의민족",
    imageUrl: "/images/placeholder-ad.svg",
    copyText: "오늘 뭐 먹지? 배민이 골라줄게 🍕",
    category: "푸드/배달",
    format: "비디오",
    likes: 5670,
    comments: 423,
    shares: 156,
    startDate: "2026-02-20",
    isActive: true,
    country: "KR",
  },
  {
    id: "4",
    platform: "facebook",
    brand: "토스",
    imageUrl: "/images/placeholder-ad.svg",
    copyText: "매달 나가는 구독료, 한눈에 확인하세요",
    category: "금융",
    format: "이미지",
    likes: 3210,
    comments: 267,
    shares: 89,
    startDate: "2026-03-05",
    isActive: true,
    country: "KR",
  },
  {
    id: "5",
    platform: "instagram",
    brand: "쿠팡",
    imageUrl: "/images/placeholder-ad.svg",
    copyText: "로켓배송으로 내일 아침에 만나요",
    category: "이커머스",
    format: "이미지",
    likes: 4100,
    comments: 312,
    shares: 78,
    startDate: "2026-03-12",
    isActive: true,
    country: "KR",
  },
  {
    id: "6",
    platform: "instagram",
    brand: "나이키",
    imageUrl: "/images/placeholder-ad.svg",
    copyText: "Just Do It. 새로운 에어맥스 컬렉션",
    category: "스포츠",
    format: "비디오",
    likes: 8900,
    comments: 654,
    shares: 234,
    startDate: "2026-02-28",
    isActive: true,
    country: "KR",
  },
  {
    id: "7",
    platform: "facebook",
    brand: "야놀자",
    imageUrl: "/images/placeholder-ad.svg",
    copyText: "놀자! 봄 특가 숙소 최대 50% 할인",
    category: "여행",
    format: "캐러셀",
    likes: 2800,
    comments: 198,
    shares: 67,
    startDate: "2026-03-08",
    endDate: "2026-03-20",
    isActive: false,
    country: "KR",
  },
  {
    id: "8",
    platform: "instagram",
    brand: "삼성전자",
    imageUrl: "/images/placeholder-ad.svg",
    copyText: "Galaxy S26 Ultra, 새로운 AI가 만드는 경험",
    category: "테크",
    format: "비디오",
    likes: 12300,
    comments: 890,
    shares: 456,
    startDate: "2026-03-01",
    isActive: true,
    country: "KR",
  },
  {
    id: "9",
    platform: "facebook",
    brand: "스타벅스",
    imageUrl: "/images/placeholder-ad.svg",
    copyText: "벚꽃 시즌 한정 음료, 지금 만나보세요 🌸",
    category: "F&B",
    format: "이미지",
    likes: 6700,
    comments: 534,
    shares: 189,
    startDate: "2026-03-15",
    isActive: true,
    country: "KR",
  },
  {
    id: "10",
    platform: "instagram",
    brand: "당근",
    imageUrl: "/images/placeholder-ad.svg",
    copyText: "우리 동네 중고 직거래, 당근에서 시작하세요",
    category: "라이프스타일",
    format: "이미지",
    likes: 3450,
    comments: 213,
    shares: 56,
    startDate: "2026-03-18",
    isActive: true,
    country: "KR",
  },
  {
    id: "11",
    platform: "instagram",
    brand: "현대자동차",
    imageUrl: "/images/placeholder-ad.svg",
    copyText: "전기차의 새로운 기준, 아이오닉 6",
    category: "자동차",
    format: "비디오",
    likes: 7800,
    comments: 432,
    shares: 198,
    startDate: "2026-02-25",
    isActive: true,
    country: "KR",
  },
  {
    id: "12",
    platform: "facebook",
    brand: "마켓컬리",
    imageUrl: "/images/placeholder-ad.svg",
    copyText: "새벽배송으로 만나는 제주 유기농 감귤",
    category: "식품",
    format: "이미지",
    likes: 1890,
    comments: 145,
    shares: 34,
    startDate: "2026-03-20",
    isActive: true,
    country: "KR",
  },
];

export const categories = [
  "전체",
  "뷰티",
  "패션",
  "푸드/배달",
  "금융",
  "이커머스",
  "스포츠",
  "여행",
  "테크",
  "F&B",
  "라이프스타일",
  "자동차",
  "식품",
];

export const platforms = ["전체", "instagram", "facebook", "meta"];
export const formats = ["전체", "이미지", "비디오", "캐러셀"];
export const sortOptions = [
  { label: "최신순", value: "latest" },
  { label: "좋아요순", value: "likes" },
  { label: "댓글순", value: "comments" },
];
